services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV: production
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/basu/storage:/home/basu/storage
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
    - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: