services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV: development
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - ENV=development
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/aakarshanbasubhardwaj/storage:/home/aakarshanbasubhardwaj/storage
      - ./backend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

# volumes:
#   backup_data: