name: Deploy to Remote Server via OpenVPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn unzip lsb-release ca-certificates curl gnupg2

    - name: Verify OpenVPN installation
      run: |
        openvpn --version

    - name: Prepare OpenVPN configuration
      run: |
        echo "${{ secrets.OPENVPN_CONFIG }}" > /tmp/openvpn-config.ovpn
        cat /tmp/openvpn-config.ovpn # Debugging: Output the OpenVPN config (for review, sensitive info will be omitted)

    - name: Connect to OpenVPN
      run: |
        sudo openvpn --config /tmp/openvpn-config.ovpn --daemon
        echo "OpenVPN process started. Checking for connection..."

    - name: Wait for VPN connection
      run: |
        sleep 10 # Wait for VPN connection
        ip a # Show the current network interfaces, including VPN interface (helpful for debugging)

    - name: Verify VPN connection
      run: |
        ifconfig # Show the network interfaces to check if VPN interface is present
        ping -c 4 8.8.8.8 # Test internet connectivity to ensure VPN is working

    - name: Install Docker
      run: |
        sudo apt-get install -y docker.io

    - name: Start Docker service
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo docker --version # Check Docker version to ensure it's running

    - name: Deploy Docker container
      run: |
        sudo docker pull <YOUR-DOCKER-IMAGE> # Pull the Docker image
        sudo docker run -d -p 80:80 <YOUR-DOCKER-IMAGE> # Start the container

    - name: Verify container is running
      run: |
        sudo docker ps # List running containers to verify deployment
