name: OpenVPN and Docker Setup

on:
  push:
    branches:
      - main

jobs:
  openvpn_docker_setup:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up OpenVPN
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          lsb-release \
          ca-certificates \
          wget \
          gnupg2 \
          curl \
          sudo \
          unzip \
          bash \
          docker.io \
          docker-compose

    # Add Docker's official GPG key and set up the stable repository
    - name: Add Docker repository
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    # Install OpenVPN 3
    - name: Install OpenVPN3
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ca-certificates \
          curl \
          gnupg \
          lsb-release \
          openvpn3

    # Save the OpenVPN configuration from secrets
    - name: Save OpenVPN config
      run: echo "${{ secrets.OPENVPN_CONFIG }}" > openvpn-client.ovpn

    # Import OpenVPN configuration and start the session
    - name: Import OpenVPN configuration and start session
      run: |
        # Import the OpenVPN config
        sudo openvpn3 config import --config openvpn-client.ovpn
        
        # Start the OpenVPN session
        sudo openvpn3 session-start --config openvpn-client.ovpn

    # Set up Docker container
    - name: Build and run Docker container
      run: |
        # Navigate to your Docker setup directory (replace with the correct path)
        cd path/to/your/docker-compose/file
        
        # Build and run the Docker container using Docker Compose
        sudo docker-compose up -d

    # Optional: Verify Docker container status
    - name: Check Docker containers status
      run: |
        sudo docker ps
