name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH to Local Machine
      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 141.99.60.213 >> ~/.ssh/known_hosts

      # Step 3: Create SSH Tunnel to Remote Server
      - name: Create SSH Tunnel
        run: |
          ssh -i ~/.ssh/id_rsa -L 2222:10.144.113.16:22 <local-user>@<local-machine-ip> -fN

      # Step 4: Deploy to Remote Server
      - name: Deploy to Remote Server
        run: |
          ssh -i ~/.ssh/id_rsa -p 2222 basu@localhost << 'EOF'
            cd /backup
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF
