name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up OpenVPN 3 repository
      run: |
        sudo add-apt-repository ppa:openvpn3/openvpn3
        sudo apt update

    - name: Install OpenVPN 3
      run: |
        sudo apt install -y openvpn3

    - name: Verify OpenVPN 3 installation
      run: |
        openvpn3 version

      - name: Set up OpenVPN connection
        run: |
          echo "${{ secrets.OPENVPN_CONFIG }}" > openvpn_config.ovpn
          sudo openvpn3 session-start --config openvpn_config.ovpn

      - name: Deploy Docker containers
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@remote-server-ip "cd /path/to/your/docker && docker-compose up -d"
