name: Deploy to Remote Server via OpenVPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and OpenVPN3
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg2 lsb-release ca-certificates curl
        curl -fsSL https://packages.openvpn.net/packages-repo.gpg | sudo tee /etc/apt/trusted.gpg.d/openvpn.asc
        DISTRO=$(lsb_release -c | awk '{print $2}')
        echo "deb http://packages.openvpn.net/openvpn3/debian $DISTRO main" | sudo tee /etc/apt/sources.list.d/openvpn-packages.list
        sudo apt-get update
        sudo apt-get install -y openvpn3

    - name: Verify OpenVPN3 installation
      run: |
        openvpn3 version

    - name: Prepare OpenVPN configuration
      run: |
        echo "${{ secrets.OPENVPN_CONFIG }}" > /tmp/openvpn-config.ovpn

    - name: Connect to OpenVPN using the configuration
      run: |
        sudo openvpn3 connect /tmp/openvpn-config.ovpn

    - name: Install Docker
      run: |
        sudo apt-get install -y docker.io

    - name: Deploy Docker container
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker
        # Pull the Docker image from your registry (adjust if you have a custom image)
        sudo docker pull <YOUR-DOCKER-IMAGE>
        # Run the Docker container
        sudo docker run -d -p 80:80 <YOUR-DOCKER-IMAGE>

    - name: Verify container is running
      run: |
        sudo docker ps
