name: Deploy with OpenVPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y lsb-release ca-certificates wget gnupg2 unzip
        sudo wget -qO - https://packages.openvpn.net/packages-repo.gpg | sudo tee /etc/apt/trusted.gpg.d/openvpn.asc
        sudo DISTRO=$(lsb_release -c | awk '{print $2}') && echo "deb http://packages.openvpn.net/openvpn3/debian $DISTRO main" | sudo tee /etc/apt/sources.list.d/openvpn-packages.list
        sudo apt update

    - name: Install OpenVPN3
      run: sudo apt install -y openvpn3

    - name: Configure and start OpenVPN
      run: |
        sudo openvpn3 config import openvpn-***.ovpn
        sudo openvpn3 session-start myvpn

    - name: Deploy Docker Container
      run: |
        docker pull your-image-name
        docker run -d your-image-name
