name: OpenVPN Setup and Docker Deployment for GitHub Actions Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Remove conflicting containerd package
    - name: Remove conflicting containerd package
      run: |
        sudo apt-get remove -y containerd containerd.io

    # Install Docker and its dependencies
    - name: Install Docker dependencies
      run: |
        sudo apt update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          software-properties-common

    # Add Docker's official GPG key
    - name: Add Docker GPG key
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc

    # Add Docker repository
    - name: Add Docker repository
      run: |
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    # Update apt package index
    - name: Update apt package index
      run: |
        sudo apt update

    # Install Docker
    - name: Install Docker
      run: |
        sudo apt install -y docker-ce docker-ce-cli containerd.io

    # Install OpenVPN 3 dependencies
    - name: Install OpenVPN 3
      run: |
        sudo apt install -y openvpn3

    # Verify OpenVPN 3 installation
    - name: Verify OpenVPN 3 installation
      run: |
        openvpn3 version

    # Save the OPENVPN_CONFIG secret to a file
    - name: Save OpenVPN config
      run: echo "${{ secrets.OPENVPN_CONFIG }}" > openvpn-client.ovpn

    # Start OpenVPN client connection using the saved .ovpn file
    - name: Start OpenVPN connection
      run: |
        sudo openvpn3 config import openvpn-client.ovpn
        sudo openvpn3 session-start myvpn

    # Test the OpenVPN connection (ping the server or check the route)
    - name: Test OpenVPN Connection
      run: |
        ping -c 4 <your_server_ip_or_domain> || echo "Ping failed. Check VPN connection."

    # Build and deploy Docker container
    - name: Build Docker image
      run: |
        docker build -t your_image_name .

    # Run Docker container
    - name: Run Docker container
      run: |
        docker run -d --name your_container_name -p 80:80 your_image_name

    # Verify Docker container is running
    - name: Verify Docker container
      run: |
        docker ps
