name: Deploy to Remote Server via OpenVPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn unzip lsb-release ca-certificates curl gnupg2

    - name: Verify OpenVPN installation
      run: |
        openvpn --version

    - name: Prepare OpenVPN configuration
      run: |
        echo "${{ secrets.OPENVPN_CONFIG }}" > /tmp/openvpn-config.ovpn

    - name: Connect to OpenVPN
      run: |
        sudo openvpn --config /tmp/openvpn-config.ovpn --daemon

    - name: Wait for VPN connection
      run: |
        sleep 10 # Allow time for the VPN to connect

    - name: Install Docker
      run: |
        sudo apt-get install -y docker.io

    - name: Deploy Docker container
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker
        # Pull the Docker image from your registry (adjust if you have a custom image)
        sudo docker pull <YOUR-DOCKER-IMAGE>
        # Run the Docker container
        sudo docker run -d -p 80:80 <YOUR-DOCKER-IMAGE>

    - name: Verify container is running
      run: |
        sudo docker ps
